---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - data-service-catalog-deployment.yaml
  - data-service-catalog-service.yaml
images:
  - name: data-service-catalog
    newName: ghcr.io/informasjonsforvaltning/data-service-catalog
    newTag: $(GIT_COMMIT_SHA)
